//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Anton
//

import Foundation

protocol ___VARIABLE_productName:identifier___Presenter: AnyObject {
    var delegate: ___VARIABLE_productName:identifier___ViewControllerDelegate? { get set }
    func viewDidLoad()
}
