//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Anton
//

import Foundation

class ___VARIABLE_productName:identifier___PresenterImpl: ___VARIABLE_productName:identifier___Presenter {

    weak var delegate: ___VARIABLE_productName:identifier___ViewControllerDelegate?

    func viewDidLoad() {

    }
}
